import React, { createContext, useContext, useState } from "react";
import { extraTranslations } from "../translations/extraLangs";

export type Language = "en" | "hi" | "te" | "ta" | "bn" | "mr" | "kn" | "ml" | "gu" | "pa";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultText?: string) => string;
}

const baseTranslations: Record<Language, Partial<Record<string, string>>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.skills": "Skills",
    "nav.projects": "Projects",
    "nav.certifications": "Certifications",
    "nav.contact": "Contact",
    "about.heading": "About Ganesh",
    "skills.heading": "Technical Weaponry",
    "projects.heading": "Futuristic Deployments",
    "certs.heading": "Verified Accomplishments",
    "experience.heading": "Chronology & Triumphs",
    "contact.heading": "Bridge the Boundary",
    "hud.status": "SYS_OK",
    "hud.timezone": "UTC",
    "role.0": "AI & Data Science Engineer",
    "role.1": "Machine Learning Enthusiast",
    "role.2": "Generative AI Developer",
    "role.3": "Full Stack Developer",
    "hero.coreIntelligence": "Core Intelligence Ready",
    "hero.name": "Ganesh Enyaram",
    "hero.description": "B.Tech undergraduate specializing in Artificial Intelligence and Data Science at Marwadi University, Rajkot. Passionate about building AI-driven solutions, leading competitive hackathons, and contributing to innovative machine learning projects.",
    "hero.contactBtn": "Contact Ganesh",
    "hero.resumeBtn": "Analyze/Get Resume",
    "hero.stats.aiChats": "AI & Data Solutions",
    "hero.stats.solved": "Core Skills Listed",
    "hero.stats.systemViews": "System Views",
    "hero.stats.won": "Hackathons & Events",
    "about.careerVision": "Career Vision & Objective",
    "about.careerVisionDesc1": "Motivated and innovative Computer Science undergraduate specializing in Artificial Intelligence and Data Science at Marwadi University, Rajkot. Passionate about building AI-driven solutions, participating in competitive hackathons, and contributing to cutting-edge machine learning projects.",
    "about.careerVisionDesc2": "Passionate about applying technical expertise and leadership skills in impactful real-world environments to solve critical issues with scalable data and machine learning pipelines.",
    "about.academicHonors": "Key Achievements",
    "about.academicHistory": "Academic History",
    "about.engineeringFocus": "Specialized Technical Focus",
    "about.edu1.degree": "B.Tech – CSE (Artificial Intelligence & Data Science)",
    "about.edu1.institution": "Marwadi University, Rajkot, Gujarat",
    "about.edu1.summary": "Currently pursuing 2nd Year. Expected Graduation: 2028. Actively specializing in machine learning algorithms, deep learning neural layers, data pipelines, and advanced predictive analysis.",
    "about.edu2.degree": "Higher Secondary Education",
    "about.edu2.institution": "Siddipet, Telangana, India",
    "about.edu2.summary": "Formed strong foundational expertise in computer fundamentals, mathematics, and science disciplines.",
    "about.ach1": "Shortlisted for the PixelVerse Offline Finale Hackathon as Team Lead, advancing to national scales.",
    "about.ach2": "Participated in Convolve 4.0, a highly prestigious Pan-IIT AI/ML Hackathon across elite institutions.",
    "about.ach3": "Earned certified certificates of completion in ET AI Hackathon & ZOMATHON 24-hr Data Hackathon.",
    "about.ach4": "Selected for the RBU Global Digital Exchange Forum focusing on Inclusive & Ethical AI for ASEAN.",
    "about.exp1.title": "AI Conversational Chatbots",
    "about.exp1.desc": "Constructing NLP processing pipelines, intent classifiers, and stateful conversational interfaces with Python.",
    "about.exp2.title": "Data Science & Dashboards",
    "about.exp2.desc": "Formulating visual reporting nodes, cleaning complex datasets, and drawing automated insights using Pandas & Matplotlib.",
    "about.exp3.title": "Predictive Classifiers",
    "about.exp3.desc": "Engineering supervised training models (classification and regression) utilizing Scikit-learn and TensorFlow.",
    "about.exp4.title": "AI & Vibe Coding",
    "about.exp4.desc": "Rapid prototyping, agile system orchestrations, and prompt optimizations to deploy smart tools at lightning speeds.",
    "skills.subtitle": "Quantified technical capabilities, programming frameworks, and soft skills validated through rigorous challenge pipelines, academics, and hackathons.",
    "skills.category": "Category",
    "skills.cat1": "Technical Core",
    "skills.cat2": "AI & ML Stack",
    "skills.cat3": "Development & Git",
    "skills.cat4": "Academic Soft Skills",
    "projects.subtitle": "Authentic engineering architectures built to implement intelligent chatbots, data visualization engines, and predictive analytics.",
    "projects.filterAll": "All Projects",
    "projects.filterAIML": "AI & ML Models",
    "projects.filterGenAI": "Conversational AI",
    "projects.filterFullStack": "Interactive Visuals",
    "projects.proj1.title": "AI-Powered Chatbot",
    "projects.proj1.desc": "Developed a conversational AI chatbot using Python and NLP techniques capable of handling domain-specific queries. Integrated machine learning models for intent classification and response generation.",
    "projects.proj1.metric": "Intent Parsing Accuracy",
    "projects.proj2.title": "Data Analysis Dashboard",
    "projects.proj2.desc": "Built an interactive data visualization dashboard using Python (Pandas, Matplotlib) to analyze large datasets. Automated data cleaning pipelines and produced actionable insights for decision-making.",
    "projects.proj2.metric": "Dataset Rows Cleaned",
    "projects.proj3.title": "Predictive ML Model",
    "projects.proj3.desc": "Trained and evaluated supervised learning models (classification & regression) using Scikit-learn and TensorFlow. Achieved high accuracy on benchmark datasets through feature engineering and hyperparameter tuning.",
    "projects.proj3.metric": "R2 Score Accuracy",
    "projects.proj4.title": "AI Assistant Subpage Companion",
    "projects.proj4.desc": "An interactive digital sandbox with responsive custom layouts reflecting academic growth, speed specs audits, and latency logs.",
    "projects.proj4.metric": "Render Vector Count",
    "projects.proj5.title": "Student Performance Ledger",
    "projects.proj5.desc": "D3/Recharts powered dashboard displaying performance tracking metrics, GPA trends, and academic behavior indexes.",
    "projects.proj5.metric": "Data Load Time Delay",
    "certs.subtitle": "Accreditations, hackathon certificates, and technical participations verified from national global platforms.",
    "certs.verifyBtn": "Verify Credential",
    "exp.subtitle": "Chronology of participations in premier hackathons, case study challenges, and international exchange forums.",
    "exp.timelineTitle": "Hackathon & Challenge Timelines",
    "exp.achievementsTitle": "Soft Skills Inventory",
    "exp.item1.role": "RBU Global Digital Exchange Forum Delegate",
    "exp.item1.org": "Inclusive AI for ASEAN and Beyond",
    "exp.item1.bullet1": "Participated in an international forum focusing on inclusive and ethical AI development for ASEAN nations and beyond.",
    "exp.item1.bullet2": "Gained exposure to global perspectives on responsible AI, policy frameworks, and cross-border collaboration.",
    "exp.item1.bullet3": "Conducted high-level dialogues regarding deployment ethics and automated system transparency.",
    "exp.item2.role": "NationBuilding Case Study Competitor",
    "exp.item2.org": "National Level Tech Case Competitions",
    "exp.item2.bullet1": "Competed in a national-level case study competition focused on technology-driven nation-building initiatives.",
    "exp.item2.bullet2": "Presented data-backed solutions addressing real-world socioeconomic challenges using AI and data science models.",
    "exp.item3.role": "Hackathon Participant & Team Lead",
    "exp.item3.org": "Leading National Hackathons (PixelVerse, Convolve, ZOMATHON)",
    "exp.item3.bullet1": "Led Team Red Dragon as Team Lead at PixelVerse National offline hackathon, coordinating technical strategy under real deadlines.",
    "exp.item3.bullet2": "Analyzed complex datasets inside ZOMATHON's 24-hr data contest and presented optimized ML insights.",
    "exp.ach1.title": "Problem Solving",
    "exp.ach1.desc": "Capable of breaking down intricate logistical hurdles and constructing robust logical solutions with high precision.",
    "exp.ach1.points": "Excellent",
    "exp.ach2.title": "Team Leadership",
    "exp.ach2.desc": "Led Team Red Dragon in highly competitive hackathon arenas. Coordinated strategy, work division, and fast project execution.",
    "exp.ach2.points": "Red Dragon Lead",
    "exp.ach3.title": "Time Management",
    "exp.ach3.desc": "Thrived in 24-hour intense hackathons like ZOMATHON, planning work chunks systematically to achieve goals on time.",
    "exp.ach3.points": "Extremely Agile",
    "exp.ach4.title": "Adaptability",
    "exp.ach4.desc": "Eagerly adapts to newly released models, SDKs, and environments. Skilled at 'vibe coding' and fast programming shifts.",
    "exp.ach4.points": "Fast Learner",
    "contact.subtitle": "Connect regarding hackathon teams, recruitment opportunities, or project discussions securely.",
    "contact.nodeSpecifications": "System Contact Details",
    "contact.hqCoordinate": "Siddipet Connection Node",
    "contact.location": "Rajkot, Gujarat, India (Marwadi Univ)",
    "contact.terminalEmail": "Verified Email Node",
    "contact.whatsapp": "WhatsApp Hotline",
    "contact.connectOuterSpace": "Send Network Payload",
    "contact.directTransmission": "Direct Transmission Grid",
    "contact.identity": "Sender Name / Role",
    "contact.returnMail": "Sender Return Email Coordinates",
    "contact.payload": "Details of Inquiry",
    "contact.placeholderIdentity": "e.g. Recruiter, Hackathon Organizer",
    "contact.placeholderEmail": "e.g. connect@industry.com",
    "contact.placeholderMessage": "Type your message regarding internships, project coordination, or interview schedule details...",
    "contact.transmitBtn": "Emit Payload Vectors",
    "contact.transmitting": "Transmitting payload...",
    "contact.bookingNode": "Interactive Booking Portal",
    "contact.targetDate": "Target Date Allocation:",
    "contact.preferredSlot": "Timeslot Frame:",
    "contact.scheduleBtn": "Reserve Interview Slot",
    "contact.success": "Message transmitted successfully! Ganesh Enyaram was notified via inbox nodes.",
    "contact.errorFail": "Failed to register contact in state node. Try again, recruiter.",
    "contact.errorOffline": "Offline error. Verify express-server cluster node status."
  },
  hi: {
    "nav.home": "होम",
    "nav.about": "परिचय",
    "nav.skills": "कौशल",
    "nav.projects": "परियोजनाएं",
    "nav.certifications": "प्रमाणपत्र",
    "nav.contact": "संपर्क",
    "about.heading": "गणेश के बारे में",
    "skills.heading": "तकनीकी कौशल",
    "projects.heading": "भविष्य के परिनियोजन",
    "certs.heading": "सत्यापित उपलब्धियां",
    "experience.heading": "कालक्रम और उपलब्धियां",
    "contact.heading": "सीमाओं को पार करें",
    "hud.status": "सिस्टम_ठीक",
    "hud.timezone": "यूटीसी",
    "role.0": "एआई और डेटा साइंस इंजीनियर",
    "role.1": "मशीन लर्निंग उत्साही",
    "role.2": "जेनरेटिव एआई डेवलपर",
    "role.3": "फुल-स्टैक डेवलपर",
    "hero.coreIntelligence": "मुख्य बुद्धिमत्ता तैयार",
    "hero.name": "गणेश एन्याराम",
    "hero.description": "एआई और डेटा साइंस में बी.टेक विशेषज्ञ। मजबूत समाधान बनाने के लिए तंत्रिका आर्किटेक्चर के साथ सांख्यिकीय सटीकता का विलय।",
    "hero.contactBtn": "गणेश से संपर्क करें",
    "hero.resumeBtn": "बायोडाटा प्राप्त करें",
    "hero.stats.aiChats": "एआई चैटबॉट और एजेंट",
    "hero.stats.solved": "हल किए गए कोडिंग समाधान",
    "hero.stats.systemViews": "सिस्टम दृश्य",
    "hero.stats.won": "हैकथॉन जीत/प्लेसमेंट",
    "about.careerVision": "करियर विजन और उद्देश्य",
    "about.careerVisionDesc1": "एआई और डेटा साइंस में विशेषज्ञता रखने वाले एक छात्र के रूप में, मेरा उद्देश्य संज्ञानात्मक सहायकों और RAG आर्किटेक्चर का नेतृत्व करना है।",
    "about.careerVisionDesc2": "मैं जटिल मॉडलों को अत्यधिक अनुकूलित उत्पादन सॉफ्टवेयर में अनुवाद करने में कामयाब रहता हूँ।",
    "about.academicHonors": "अकादमिक सम्मान",
    "about.academicHistory": "अकादमिक इतिहास",
    "about.engineeringFocus": "विशेष इंजीनियरिंग फोकस",
    "about.edu1.degree": "बी.टेक इन आर्टिफिशियल इंटेलिजेंस एंड डेटा साइंस",
    "about.edu1.institution": "वर्धमान कॉलेज ऑफ इंजीनियरिंग, हैदराबाद",
    "about.edu1.summary": "मशीन लर्निंग, जेनरेटिव एआई और क्लाउड आर्किटेक्चर पर ध्यान केंद्रित। सीजीपीए: 9.2/10।",
    "about.edu2.degree": "इंटरमीडिएट शिक्षा (एमपीसी)",
    "about.edu2.institution": "एसआर जूनियर कॉलेज",
    "about.edu2.summary": "गणित, भौतिकी और रसायन विज्ञान में 98.2% स्कोर के साथ शैक्षणिक उत्कृष्टता।",
    "about.ach1": "हैकइंडिया 2025 के एलीट नेशनल टियर में स्थान।",
    "about.ach2": "स्मार्ट ओपनसीवी अटेंडेंस ट्रैकर के लिए प्रथम पुरस्कार।",
    "about.ach3": "जीपीए के आधार पर शैक्षणिक उत्कृष्टता छात्रवृत्ति।",
    "about.ach4": "लीटकोड और हैकररैंक पर 400 से अधिक कोडिंग समस्याएं हल कीं।",
    "about.exp1.title": "जेनरेटिव एआई सिस्टम",
    "about.exp1.desc": "एलएलएम, फ़ाइन-ट्यूनिंग, आरएजी और एआई एजेंट नेटवर्क का उपयोग करके मजबूत सिस्टम का निर्माण।",
    "about.exp2.title": "पूर्वानुमानित विश्लेषण और एमएल",
    "about.exp2.desc": "डीप वर्गीकरण और प्रतिगमन पाइपलाइन, सांख्यिकीय विश्लेषण और क्लस्टरिंग।",
    "about.exp3.title": "एजेंटिक इंजीनियरिंग",
    "about.exp3.desc": "क्रूएआई, लैंगचेन और लैंगग्राफ जैसे आर्केस्ट्रेशन फ्रेमवर्क का उपयोग कर मल्टी-एजेंट कोआर्डिनेशन।",
    "about.exp4.title": "मजबूत फुल-स्टैक ऐप्स",
    "about.exp4.desc": "रिएक्ट, नेक्स्ट.जेएस, नोड.जेएस और डेटाबेस का उपयोग कर रिस्पॉन्सिव डैशबोर्ड डिज़ाइन।",
    "skills.subtitle": "हैकथॉन, शैक्षणिक प्रयोगशालाओं और ओपन-सोर्स अनुप्रयोगों में कौशल मूल्यांकन।",
    "skills.category": "श्रेणी",
    "skills.cat1": "प्रोग्रामिंग",
    "skills.cat2": "एआई और एमएल",
    "skills.cat3": "डेवलपमेंट",
    "skills.cat4": "क्लाउड और डेवऑप्स",
    "projects.subtitle": "एज कंप्यूटिंग और आधुनिक जनरेटिव पाइपलाइनों के साथ निर्मित व्यावहारिक आर्किटेक्चर।",
    "projects.filterAll": "सभी",
    "projects.filterAIML": "एआई और एमएल",
    "projects.filterGenAI": "जेनरेटिव एआई",
    "projects.filterFullStack": "फुल-स्टैक",
    "projects.proj1.title": "एजेंटिक रिज्यूमे एनालाइजर और एटीएस बेंचमार्कर",
    "projects.proj1.desc": "उन्नत आरएजी पाइपलाइन संरचनात्मक खामियों का विश्लेषण करती है और जॉब विवरण के साथ बायोडाटा का मिलान करती है।",
    "projects.proj1.metric": "मिलान परिशुद्धता लाभ",
    "projects.proj2.title": "स्मार्ट ओपनसीवी एज अटेंडेंस ट्रैकर",
    "projects.proj2.desc": "स्थानीय कक्षा उपस्थिति पर नजर रखने वाला उच्च प्रदर्शन वाला फेशियल रिकग्निशन आर्किटेक्चर।",
    "projects.proj2.metric": "ट्रैकिंग फ्रेम देरी",
    "projects.proj3.title": "मल्टी-एजेंट पोर्टफोलियो वार्तालाप साथी",
    "projects.proj3.desc": "गणेश का प्रतिनिधित्व करने वाला डिजिटल अवतार। वॉयस प्रतिक्रिया जनरेटर और कौशल व्याख्याकार से सुसज्जित।",
    "projects.proj3.metric": "क्वेरी समाधान सटीकता",
    "projects.proj4.title": "स्वायत्त जनरेटिव मल्टी-मोडल सहायक",
    "projects.proj4.desc": "स्थिर प्रसार चेकप्वाइंट के साथ जोड़ा गया संवादी स्वचालन। अनुकूलित संदर्भ निर्माता और फिल्टर शामिल।",
    "projects.proj4.metric": "छवि संश्लेषण विलंबता",
    "projects.proj5.title": "गतिशील छात्र प्रदर्शन विश्लेषण पैनल",
    "projects.proj5.desc": "GPA रुझान और प्रदर्शन प्रदर्शित करने वाला डी3/रीचार्ट्स डैशबोर्ड। रेस्ट राउटर को एकीकृत करता है।",
    "projects.proj5.metric": "डेटाबेस क्वेरी फ़ेच देरी",
    "certs.subtitle": "औपचारिक क्लाउड मान्यता और डीप-लर्निंग विशेष प्रोफाइल।",
    "certs.verifyBtn": "प्रमाणपत्र सत्यापित करें",
    "exp.subtitle": "व्यावहारिक विकास समयसीमा और महत्वपूर्ण मील के पत्थर।",
    "exp.timelineTitle": "करियर की समयसीमा और प्रयोगशालाएं",
    "exp.achievementsTitle": "प्रमुख उपलब्धियां",
    "exp.item1.role": "जेनरेटिव एआई अनुसंधान इंटर्न",
    "exp.item1.org": "हेक्सामाइंड रिसर्च लैब्स",
    "exp.item1.bullet1": "क्रूएआई के साथ कस्टम संदर्भ एजेंटों का निर्माण, जिसमें 35% की गति मिली।",
    "exp.item1.bullet2": "स्थानीय सीपीयू आर्किटेक्चर पर प्रतिक्रिया बेहतर करने हेतु प्रॉम्प्ट और क्वांटाइजेशन अनुकूलन किया।",
    "exp.item1.bullet3": "विश्वविद्यालय के शोध लॉग के लिए इंटरैक्टिव डेटा अन्वेषण सक्षम करने वाला आरएजी इंटरफ़ेस बनाया।",
    "exp.item2.role": "फुल स्टैक इंजीनियर (फ्रीलांस)",
    "exp.item2.org": "स्थानीय स्टार्टअप परामर्श अनुबंध",
    "exp.item2.bullet1": "React 19 और Node.js का उपयोग करके रोगियों के लिए बुकिंग डैशबोर्ड तैयार किया।",
    "exp.item2.bullet2": "डेटाबेस इंडेक्सिंग रणनीतियों द्वारा एपीआई रिस्पॉन्स समय को 240ms से घटाकर 75ms किया।",
    "exp.item3.role": "हैकइंडिया राष्ट्रीय प्रतियोगी",
    "exp.item3.org": "राष्ट्रीय स्तर के शीर्ष 2% विजेता",
    "exp.item3.bullet1": "36 घंटे से कम समय में ब्लॉकचेन सैंडबॉक्स पर विकेंद्रीकृत सत्यापन इंजन का निर्माण किया।",
    "exp.item3.bullet2": "देश भर के 5000+ अर्हक उम्मीदवारों में से शीर्ष 2% स्थान हासिल किया।",
    "exp.ach1.title": "लीटकोड विशेषज्ञ",
    "exp.ach1.desc": "400 से अधिक एल्गोरिथम समस्याओं को हल किया। ग्राफ, डायनेमिक प्रोग्रामिंग और गणितीय कोडिंग के कुशल।",
    "exp.ach1.points": "विश्व स्तर पर शीर्ष 7%",
    "exp.ach2.title": "स्मार्ट ओपनसीवी विजेता",
    "exp.ach2.desc": "अटेंडेंस ट्रैकर के लिए इनोवेशन फेयर में कॉलेज द्वारा प्रथम पुरस्कार से सम्मानित।",
    "exp.ach2.points": "इनोवेशन चैंपियन",
    "exp.ach3.title": "ओपन सोर्स योगदानकर्ता",
    "exp.ach3.desc": "लोकप्रिय आरएजी और रिएक्ट ओपन-सोर्स रैपर्स में कोडिंग योगदान दिया।",
    "exp.ach3.points": "सक्रिय गिटहब प्रोफाइल",
    "exp.ach4.title": "एलीट शैक्षणिक स्तर",
    "exp.ach4.desc": "इंजीनियरिंग पाठ्यक्रम के दौरान लगातार उत्कृष्ट 9.2 सीजीपीए बनाए रखा।",
    "exp.ach4.points": "9.2 कोर सीजीपीए",
    "contact.subtitle": "कार्यक्षेत्र कैलेंडर बुक करें, सीधे संदेश भेजें, या सीधे व्हाट्सएप संपर्क शुरू करें।",
    "contact.nodeSpecifications": "नोड विवरण",
    "contact.hqCoordinate": "मुख्यालय स्थान",
    "contact.location": "हैदराबाद, तेलंगाना, भारत",
    "contact.terminalEmail": "ईमेल पता",
    "contact.whatsapp": "व्हाट्सएप हॉटलिंक",
    "contact.connectOuterSpace": "अन्य संपर्क",
    "contact.directTransmission": "सीधा संदेश ट्रांसमिशन",
    "contact.identity": "आपकी पहचान",
    "contact.returnMail": "रिटर्न ईमेल सर्वर",
    "contact.payload": "संदेश सामग्री",
    "contact.placeholderIdentity": "जैसे भर्तीकर्ता, तकनीकी प्रमुख",
    "contact.placeholderEmail": "जैसे lead@google.com",
    "contact.placeholderMessage": "साक्षात्कार कार्यक्रम, परियोजना समीक्षा, या अनुबंध भूमिकाओं के बारे में पूछें...",
    "contact.transmitBtn": "सुरक्षित संदेश भेजें",
    "contact.transmitting": "वेक्टर प्रेषित किए जा रहे हैं...",
    "contact.bookingNode": "स्वचालित बुकिंग नोड",
    "contact.targetDate": "लक्ष्य तिथि चुनें:",
    "contact.preferredSlot": "पसंदीदा समय:",
    "contact.scheduleBtn": "बैठक निर्धारित करें",
    "contact.success": "संदेश सफलतापूर्वक भेजा गया। गणेश को सूचित कर दिया गया है।",
    "contact.errorFail": "संदेश भेजने में विफल। कृपया पुन: प्रयास करें।",
    "contact.errorOffline": "ऑफ़लाइन त्रुटि। कृपया अपने नेटवर्क कनेक्शन की जाँच करें।"
  },
  te: {
    "nav.home": "హోమ్",
    "nav.about": "పరిచయం",
    "nav.skills": "నైపుణ్యాలు",
    "nav.projects": "ప్రాజెక్టులు",
    "nav.certifications": "సర్టిఫికెట్లు",
    "nav.contact": "సంప్రదించండి",
    "about.heading": "గణేష్ గురించి",
    "skills.heading": "సాంకేతిక నైపుణ్యాలు",
    "projects.heading": "ప్రాజెక్టుల విభాగం",
    "certs.heading": "ధృవీకరించబడిన విజయాలు",
    "experience.heading": "అనుభవాలు & విజయాలు",
    "contact.heading": "కనెక్ట్ అవ్వండి",
    "hud.status": "సిస్టమ్_ఓకే",
    "hud.timezone": "యుటిసి",
    "role.0": "AI & డేటా సైన్స్ ఇంజనీర్",
    "role.1": "మెషిన్ లెర్నింగ్ నిపుణుడు",
    "role.2": "జెనరేటివ్ AI డెవలపర్",
    "role.3": "ఫుల్ స్టాక్ డెవలపర్",
    "hero.coreIntelligence": "ఇంటెలిజెన్స్ సిద్దంగా ఉంది",
    "hero.name": "గణేష్ ఎన్యారం",
    "hero.description": "AI & డేటా సైన్స్ లో B.Tech ఇంజనీరింగ్. అధునాతన న్యూరల్ పద్ధతులతో స్మార్ట్ ఫుల్ స్టాక్ యాప్ ల రూపకల్పన.",
    "hero.contactBtn": "సంప్రదించండి",
    "hero.resumeBtn": "రెజ్యూమే పొందండి",
    "hero.stats.aiChats": "AI చాట్‌బాట్లు & ఏజెంట్లు",
    "hero.stats.solved": "సాధించిన సమస్యలు",
    "hero.stats.systemViews": "సిస్టమ్ వీక్షణలు",
    "hero.stats.won": "హ్యాకథాన్ విజయాలు",
    "about.careerVision": "కెరీర్ లక్ష్యం",
    "about.careerVisionDesc1": "ఆశావాహ AI & డేటా సైన్స్ విద్యార్థిగా స్మార్ట్ RAG ఆర్కిటెక్చర్లు మరియూ యూజర్ అనుభవాలను నిర్మించడం నా ధ్యేయం.",
    "about.careerVisionDesc2": "క్లిష్టమైన గణిత శాస్త్ర నమూనాలను అత్యుత్తమ సాఫ్ట్‌వేర్‌లుగా మార్చడంలో నేను నిపుణుడిని.",
    "about.academicHonors": "అకడమిక్ పురస్కారాలు",
    "about.academicHistory": "విద్యాభ్యాసం",
    "about.engineeringFocus": "ప్రత్యేక నైపుణ్యం",
    "about.edu1.degree": "B.Tech ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ & డేటా సైన్స్",
    "about.edu1.institution": "వర్ధమాన్ ఇంజనీరింగ్ కాలేజీ, హైదరాబాద్",
    "about.edu1.summary": "అధునాతన మెషిన్ లెర్నింగ్, జెనరేటివ్ AI మరియు క్లౌడ్ ప్లాట్‌ఫార్మ్స్. CGPA: 9.2/10.",
    "about.edu2.degree": "ఇంటర్మీడియట్ విద్యాభ్యాసం (MPC)",
    "about.edu2.institution": "SR జూనియర్ కాలేజీ",
    "about.edu2.summary": "గణితం, భౌతిక శాస్త్రం మరియు రసాయన శాస్త్రం లలో 98.2% సగటు మార్కులతో ప్రతిభ.",
    "about.ach1": "హ్యాక్‌ఇండియా 2025 లీగ్ జాతీయ స్థాయిలో ఎంపిక.",
    "about.ach2": "స్మార్ట్ OpenCV అటెండెన్స్ సిస్టమ్ రూపకల్పనకు ప్రథమ బహుమతి.",
    "about.ach3": "నిరంతర విద్యా ప్రతిభా స్కాలర్‌షిప్ పురస్కారాలు.",
    "about.ach4": "లీట్‌కోడ్ మరియు హ్యాకర్‌రాంక్ పై 400 కు పైగా కోడింగ్ సమస్యలు సాధన.",
    "about.exp1.title": "జెనరేటివ్ AI సొల్యూషన్స్",
    "about.exp1.desc": "LLMలు, ఫైన్-ట్యూనింగ్, RAG మరియు ఏజెంట్ ఫ्रेమ్‌వర్క్‌లను ఉపయోగించి బలమైన వ్యవస్థలను నిర్మించడం.",
    "about.exp2.title": "ప్రిడిక్టివ్ అనలిటిక్స్ & ML",
    "about.exp2.desc": "వర్గీకరణ, రిగ్రెషన్ పైప్‌లైన్‌లు, గణాంక విశ్लेషణ, క్लస్టరింగ్ మరియు డేటాసెట్ పరివర్తనాలు.",
    "about.exp3.title": "ఏజెంట్ ఇంజనీరింగ్",
    "about.exp3.desc": "crewAI, LangChain మరియు LangGraph లతో మల్టీ-ఏజెంట్ కోఆర్డినేషన్ సిస్టమ్స్.",
    "about.exp4.title": "ఫుల్ స్టాక్ అప్లికేషన్లు",
    "about.exp4.desc": "React, Next.js, Node.js తో కూడిన అద్భుతమైన మరియు వేగవంతమైన డాష్‌బోర్డులు.",
    "skills.subtitle": "హ్యాకథాన్లు, అకడమిక్ లాబ్స్ మరియు వెబ్ ప్రాజెక్టులలో చూపిన ప్రదర్శన.",
    "skills.category": "విభాగం",
    "skills.cat1": "ప్రోగ్రామింగ్",
    "skills.cat2": "AI & ML",
    "skills.cat3": "డెవలప్‌మెంట్",
    "skills.cat4": "క్లౌడ్ & డెవాప్స్",
    "projects.subtitle": "క్లౌడ్ మరియు ల్యాటెన్సీ లేని సిస్టమ్స్ నిర్మాణం.",
    "projects.filterAll": "అన్నీ",
    "projects.filterAIML": "AI & ML",
    "projects.filterGenAI": "జెనరేటివ్ AI",
    "projects.filterFullStack": "ఫుల్ స్టాక్",
    "projects.proj1.title": "ఏజెంట్ రెజ్యూమే అనలైజర్ & ATS బెంచ్‌మార్కర్",
    "projects.proj1.desc": "ఉన్నత RAG పైప్‌లైన్లు స్ట్రక్చరల్ లోపాలను విశ్लेషిస్తాయి మరియు నిర్దిష్ట జాబ్ డిస్క్రిప్షన్‌లతో రెజ్యూమేలను సరిపోల్చుతాయి.",
    "projects.proj1.metric": "సరిపోలిక ఖచ్చితత్వం మెరుగుదల",
    "projects.proj2.title": "స్మార్ట్ OpenCV ఎడ్జ్ అటెండెన్స్ ట్రాకర్",
    "projects.proj2.desc": "క్లాస్‌రూమ్ అటెండెన్స్‌ను పర్యవేక్షించే వేగవంతమైన ఫేషియల్ రికగ్నిషన్ సిస్టమ్.",
    "projects.proj2.metric": "ట్రాకింగ్ ఫ్రేమ్ ఆలస్యం",
    "projects.proj3.title": "మల్టీ-ఏజెంట్ పోర్ట్‌ఫోలియో సంభాషణ సహాయకుడు",
    "projects.proj3.desc": "గణేష్ డిజిటల్ అవతార్. వాయిస్ సపోర్ట్ మరియూ స్మార్ట్ నైపుణ్యాల వివరణలతో కూడినది.",
    "projects.proj3.metric": "ప్రశ్నల నివృత్తి ఖచ్చితత్వం",
    "projects.proj4.title": "స్వయంప్రతిపత్తి గల మల్టీ-మోడల్ అసిస్టెంట్",
    "projects.proj4.desc": "Stable Diffusion తో టెక్స్ట్ నుంచి ఇమేజ్ సృష్టించే అధునాతన అసిస్టెంట్.",
    "projects.proj4.metric": "ఇమేజ్ జనరేషన్ సమయం",
    "projects.proj5.title": "విద్యార్థి ప్రదర్శన అనలిటిక్స్ డాష్‌బోర్ड",
    "projects.proj5.desc": "D3/Recharts ద్వారా విద్యార్థుల మార్కులు మరియూ ప్రవర్తనను పర్యవేక్షించే ప్యానెల్.",
    "projects.proj5.metric": "డేటాబేస్ లోడ్ సమయం",
    "certs.subtitle": "అధికారిక సంస్థల ద్వారా ధృవీకరించబడిన క్లౌడ్ మరియు డీప్ లెర్నింగ్ సర్టిఫికెట్లు.",
    "certs.verifyBtn": "ధృవీకరణ పత్రాన్ని తనిखీ చేయి",
    "exp.subtitle": "శిక్షణ, హ్యాకథాన్లు మరియు రీసెర్చ్ ఇంటర్న్‌షిప్ ల ప్రयाణం.",
    "exp.timelineTitle": "కెరీర్ టైమ్‌లైన్",
    "exp.achievementsTitle": "ముఖ్యమైన విజయాలు",
    "exp.item1.role": "జెనరేటివ్ AI రీసెర్చ్ ఇంటర్న్",
    "exp.item1.org": "హెక్సామైండ్ రీసెర్చ్ ల్యాబ్స్",
    "exp.item1.bullet1": "crewAI ఏజెంట్లతో డేటా విశ్లేషణ వేగాన్ని 35% పెంపొందించడం.",
    "exp.item1.bullet2": "CPU లపై స్థానిక LLM పనుల ల్యాటెన్సీ తగ్గించడానికి క్వాంటైజేషన్ పద్ధతులు అమలు చేయుట.",
    "exp.item1.bullet3": "యూనివర్సిటీ తీసిస్ శోధన కోసం ఇంటరాక్టిव RAG ఇంటర్ఫేస్ రూపకల్పన.",
    "exp.item2.role": "ఫుల్ స్టాక్ ఇంజనీర్ (ఫ్రీలాన్స్)",
    "exp.item2.org": "టెక్ స్టార్టప్‌ల సంప్రదింపు ఒప్పందాలు",
    "exp.item2.bullet1": "React 19 మరియు Node తో రోగుల రిజర్వేషన్ డాష్‌బోర్డ్ సృష్టి.",
    "exp.item2.bullet2": "డేటాబేస్ ఆప్టిమైజేషన్ తో API ల్యాటెన్సీని 240ms నుండి 75ms కి తగ్గించుట.",
    "exp.item3.role": "హ్యాక్‌ఇండియా జాతీయ హ्याకథాన్ రన్నరప్",
    "exp.item3.org": "నేషనల్ ఎలైట్ 2% విజేతలు",
    "exp.item3.bullet1": "36 గంటల కన్నా తక్కువ వ్యవధిలో పూర్తి స్థాయి వెరిఫికేషన్ సిస్టమ్ రూపకల్పన.",
    "exp.item3.bullet2": "దేశవ్యాప్తంగా 5000+ అభ్యర్థులలో టాప్ 2% లో నిలవడం.",
    "exp.ach1.title": "లీట్‌కోడ్ నిపుణుడు",
    "exp.ach1.desc": "400 కి పైగా క్లిష్టమైన సమస్యల సాధన. గ్రాఫ్స్ మరియు డైనమిಕ್ కోడింగ్ నైపుణ్యం.",
    "exp.ach1.points": "ప్రపంచవ్యాప్తంగా టాప్ 7%",
    "exp.ach2.title": "OpenCV విజేత",
    "exp.ach2.desc": "ఫేషియల్ రికగ్నిషన్ అటెండెన్స్ సిస్టమ్ ఆవిష్కరణకు ప్రథమ బహుమతి లభించింది.",
    "exp.ach2.points": "ఇన్నోవేషన్ ఛాంపియన్",
    "exp.ach3.title": "ఓపెన్ సోర్స్ డెవలపర్",
    "exp.ach3.desc": "ప్రముఖ RAG టూల్స్ మరియు రియాక్ట్ లైబ్రరీలలో లోపాలను సరిదిద్దడం.",
    "exp.ach3.points": "యాక్టివ్ గిట్‌హబ్ ప్రొఫైల్",
    "exp.ach4.title": "అత్యుత్తమ విద్యా ప్రతిభ",
    "exp.ach4.desc": "ఇంజనీరింగ్ ఆల్ సెమిస్టర్ ల లో నిరంతరం 9.2 CGPA స్కోరు సాధించుట.",
    "exp.ach4.points": "9.2 కోర్ CGPA",
    "contact.subtitle": "మీటింగ్‌లు షెడ్యూల్ చేయండి, నేరుగా సందేశం పంపండి లేదా వాట్సాప్ ద్వారా మాట్లాడండి.",
    "contact.nodeSpecifications": "సాంకేతిక వివరాలు",
    "contact.hqCoordinate": "ప్రధాన కేంద్రం",
    "contact.location": "హైదराबाद, తెలంగాణ, భారతదేశం",
    "contact.terminalEmail": "ఈమెయిల్ చిరునామా",
    "contact.whatsapp": "వాట్సాప్ హాట్‌లింక్",
    "contact.connectOuterSpace": "ఇతర నెట్‌వర్క్‌లు",
    "contact.directTransmission": "ప్రత్యక్ష సందేశం",
    "contact.identity": "మీ పేరు/హోదా",
    "contact.returnMail": "తిరుగు ఈమెయిల్",
    "contact.payload": "సందేశ సారాంశం",
    "contact.placeholderIdentity": "ఉదా. రిక్రూటర్, ప్రాజెక్ట్ మేనేజర్",
    "contact.placeholderEmail": "ఉదా. lead@google.com",
    "contact.placeholderMessage": "మీ అభిప్రాయాలు లేదా మీటింగ్ వివరాలు ఇక్కడ రాయండి...",
    "contact.transmitBtn": "సందేశం పంపండి",
    "contact.transmitting": "సందేశం వెళ్తోంది...",
    "contact.bookingNode": "షెడ్యూలింగ్ మీట్",
    "contact.targetDate": "తేదీ ని ఎంచుకోండి:",
    "contact.preferredSlot": "సమయాన్ని ఎంచుకోండి:",
    "contact.scheduleBtn": "మీటింగ్ షెడ్యూల్ చేయి",
    "contact.success": "సందేశాన్ని విజయవంతంగా పంపాము! గణేష్ త్వరలోనే స్పందిస్తారు.",
    "contact.errorFail": "సందేశం పంపడం వీలుకాలేదు. తిరిగి ప్రయత్నించండి.",
    "contact.errorOffline": "సర్వర్ తో కనెక్టివిటీ లోపం ఉంది."
  },
  ta: {
    "nav.home": "முகப்பு",
    "nav.about": "விவரம்",
    "nav.skills": "திறன்கள்",
    "nav.projects": "திட்டங்கள்",
    "nav.certifications": "சான்றிதழ்கள்",
    "nav.contact": "தொடர்பு",
    "about.heading": "கணேஷ் பற்றி",
    "skills.heading": "தொழில்நுட்ப திறன்கள்",
    "projects.heading": "அதிநவீன திட்டங்கள்",
    "certs.heading": "சான்றுகள்",
    "experience.heading": "பயணம் மற்றும் சாதனைகள்",
    "contact.heading": "தொடர்பு கொள்ள",
    "hud.status": "சரி",
    "hud.timezone": "யுடிசி",
    "role.0": "AI & தரவு அறிவியல் பொறியாளர்",
    "role.1": "மெஷின் லேர்னிங் ஆர்வலர்",
    "role.2": "ஜெனரேட்டிவ் AI டெவலப்பர்",
    "role.3": "புல் ஸ்டாக் டெவலப்பர்",
    "hero.coreIntelligence": "புத்திசாலித்தனம் தயார்",
    "hero.name": "கணேஷ் என்யாரம்",
    "hero.description": "AI & தரவு அறிவியலில் பி.டெக் நிபுணர். న్యూరல் ஆர்கிடெக்சருடன் முழுமையான செயலிகளை உருவாக்குபவர்.",
    "hero.contactBtn": "தொடர்பு கொள்ள",
    "hero.resumeBtn": "ரெஸ்யூம் பெற",
    "hero.stats.aiChats": "AI சாட்போட்கள் & முகவர்கள்",
    "hero.stats.solved": "தீர்க்கப்பட்ட குறியீடுகள்",
    "hero.stats.systemViews": "கணினி பார்வைகள்",
    "hero.stats.won": "ஹேக்கத்தான் வெற்றிகள்",
    "about.careerVision": "தொழில் நோக்கம்",
    "about.careerVisionDesc1": "AI & தரவு அறிவியல் மாணவராக சிறந்த RAG மற்றும் பயனர் இடைமுகத்தை உருவாக்குவதே எனது லட்சியம்.",
    "about.careerVisionDesc2": "சிக்கலான கணித மாதிரிகளை உயர்தர உற்பத்தி மென்பொருளாக மாற்றுவதில் நான் வல்லவர்.",
    "about.academicHonors": "கல்வி விருதுகள்",
    "about.academicHistory": "கல்வி விவரம்",
    "about.engineeringFocus": "சிறப்பு பொறியியல் கவனம்",
    "about.edu1.degree": "B.Tech செயற்கை நுண்ணறிவு & தரவு அறிவியல்",
    "about.edu1.institution": "வர்தமான் பொறியியல் கல்லூரி, ஹைதராபாத்",
    "about.edu1.summary": "மேம்பட்ட மெஷின் லேர்னிங், ஜெனரேட்டிவ் AI மற்றும் கிளவுட் ஆர்கிடெக்சர். சிஜிபிஏ: 9.2/10.",
    "about.edu2.degree": "இடைநிலை கல்வி (MPC)",
    "about.edu2.institution": "SR ஜூனியர் காலேஜ்",
    "about.edu2.summary": "கணிதம், இயற்பியல் மற்றும் வேதியியலில் 98.2% மதிப்பெண்களுடன் கல்விச் சிறப்பு.",
    "about.ach1": "ஹேக்இந்தியா 2025 தகுதிப் பட்டியலில் தேசிய அளவில் தேர்வு.",
    "about.ach2": "OpenCV வருகைப் பதிவு முனைய உருவாக்கத்திற்காக முதல் பரிசு.",
    "about.ach3": "கல்வித் தகுதிக்கான தொடர்ச்சியான உதவித்தொகை விருதுகள்.",
    "about.ach4": "லீட்கோடு மற்றும் ஹேக்கர் ரேங்க்கில் 400 க்கும் மேற்பட்ட பிரச்சனைகளுக்கு தீர்வு.",
    "about.exp1.title": "ஜெனரேட்டிவ் AI அமைப்புகள்",
    "about.exp1.desc": "LLMகள், ஃபைன்-டியூனிங் மற்றும் RAG தொழில்நுட்பத்துடன் சிறந்த முகவர்கள் உருவாக்கம்.",
    "about.exp2.title": "முன்கணிப்பு பகுப்பாய்வு & ML",
    "about.exp2.desc": "வகைப்பாடு, பின்னடைவு மற்றும் புள்ளியியல் பகுப்பாய்வு மூலம் தரவு செயலாக்கம்.",
    "about.exp3.title": "ஏஜென்ட் இன்ஜினியரிங்",
    "about.exp3.desc": "crewAI, LangChain மற்றும் LangGraph மூலம் பல முகவர்களின் ஒருங்கிணைப்பு.",
    "about.exp4.title": "முழுமையான செயலிகள்",
    "about.exp4.desc": "React, Next.js, Node.js கொண்டு வடிவமைக்கப்பட்ட அதிவேக விபரப் பலகைகள்.",
    "skills.subtitle": "போட்டிகள் மற்றும் கல்வி ஆய்வகங்களில் மதிப்பிடப்பட்ட தொழில்நுட்பத் திறன்கள்.",
    "skills.category": "பிரிவு",
    "skills.cat1": "நிரலாக்கம்",
    "skills.cat2": "AI & ML",
    "skills.cat3": "மேம்பாடு",
    "skills.cat4": "கிளவுட் & டெவஆப்ஸ்",
    "projects.subtitle": "எட்ஜ் கம்ப்யூட்டிங் மற்றும் நவீன ஜெனரேட்டிவ் தொழில்நுட்பங்களைக் கொண்டு உருவாக்கப்பட்டவை.",
    "projects.filterAll": "அனைத்தும்",
    "projects.filterAIML": "AI & ML",
    "projects.filterGenAI": "ஜெனரேட்டிவ் AI",
    "projects.filterFullStack": "புல் ஸ்டாக்",
    "projects.proj1.title": "ஏஜென்டிக் ரெஸ்யூம் பகுப்பாய்வி & ATS மதிப்பீட்டாளர்",
    "projects.proj1.desc": "பணி விளக்கங்களுடன் ரெஸ்யூம்களை ஒப்பிட்டுப் பார்க்கும் மேம்பட்ட RAG செயலி.",
    "projects.proj1.metric": "பொருத்தத்தின் துல்லியம்",
    "projects.proj2.title": "OpenCV எட்ஜ் வருகைப் பதிவு சாதனம்",
    "projects.proj2.desc": "முக அங்கீகாரம் மூலம் வருகையைப் பதிவு செய்யும் அதிவேக ஸ்மார்ட் கேமரா செயலி.",
    "projects.proj2.metric": "பகுப்பாய்வு வேகம்",
    "projects.proj3.title": "பல முகவர்கள் கொண்ட போர்ட்ஃபோலியோ துணையாள்",
    "projects.proj3.desc": "குரல் ஆதரவுடன் கணேஷின் திறமைகளை விளக்கும் ஸ்மார்ட் டிஜிட்டல் அவதார்.",
    "projects.proj3.metric": "துல்லியமான பதில்கள்",
    "projects.proj4.title": "தன்னாட்சி மல்டி மாடல் முகவர்",
    "projects.proj4.desc": "வார்த்தைகளில் இருந்து ஸ்டேபிள் டிப்யூஷன் மூலம் படம் உருவாக்கும் செயலி.",
    "projects.proj4.metric": "படம் உருவாக்க நேரம்",
    "projects.proj5.title": "மாணவர் செயல்திறன் பகுப்பாய்வு பலகை",
    "projects.proj5.desc": "D3/Recharts கொண்டு மாணவர்களின் மதிப்பெண்களை பகுப்பாய்வு செய்யும் வரைபட செயலி.",
    "projects.proj5.metric": "தரவுத்தள வேகம்",
    "certs.subtitle": "நறுவனங்களால் வழங்கப்பட்ட கிளவுட் தொழில்நுட்பம் மற்றும் ஆழமான கற்றல் சான்றிதழ்கள்.",
    "certs.verifyBtn": "சான்றை சரிபார்க்க",
    "exp.subtitle": "ஹேக்கத்தான்கள், வேலை வாய்ப்பு தேர்வுகள் மற்றும் ஆராய்ச்சிப் பயிற்சிகள் மூலம் பெறப்பட்ட நடைமுறை அனுபவங்கள்.",
    "exp.timelineTitle": "தொழில்முறை காலவரிசை",
    "exp.achievementsTitle": "முக்கிய சாதனைகள்",
    "exp.item1.role": "ஜெனரேட்டிவ் AI ஆராய்ச்சி உதவியாளர்",
    "exp.item1.org": "HexaMind ஆராய்ச்சி ஆய்வகம்",
    "exp.item1.bullet1": "crewAI மூலம் தனிப்பயன் முகவர்களை உருவாக்கி தரவு பகுப்பாய்வை 35% வேகப்படுத்தியது.",
    "exp.item1.bullet2": "CPU கட்டமைப்புகளில் லேட்டன்சியை குறைக்க குவாண்ட்டைசேஷன் மற்றும் வெக்டர் உட்பொதிப்புகளைப் பயன்படுத்தியது.",
    "exp.item1.bullet3": "பல்கலைக்கழக ஆய்வேடுகளின் தரவை ஆராய ஒரு ஊداءடும் RAG இடைமுகத்தை உருவாக்கியது.",
    "exp.item2.role": "முழுது அடுக்கு பொறியாளர் (ஃப்ரீலான்ஸ்)",
    "exp.item2.org": "உள்ளூர் ஸ்டார்ட்அப்களுக்கான ஆலோசகர்",
    "exp.item2.bullet1": "React 19 மற்றும் Node கொண்டு மொபைலில் இயங்கும் நோயாளி முன்பதிవు பக்கத்தை உருவாக்கியது.",
    "exp.item2.bullet2": "தரவுத்தள குறியீட்டு உத்திகள் மூலம் API லேட்டன்சியை 240ms லிருந்து 75ms ஆக குறைத்தது.",
    "exp.item3.role": "ஹேக்இந்தியா தேசிய போட்டியாளர்",
    "exp.item3.org": "தேசிய எலைட் 2% குழு",
    "exp.item3.bullet1": "36 மணிநேரத்தில் பரவலாக்கப்பட்ட சரிபார்ப்பு பொறியை உருவாக்கியது.",
    "exp.item3.bullet2": "தேசிய அளவில் சிறந்த உத்திகளை வகுத்தவர்களில் இடம்பிடித்தது.",
    "exp.ach1.title": "லீட்கோடு நிபுணர்",
    "exp.ach1.desc": "400 க்கும் மேற்பட்ட சிக்கலான அல்காரிதம் மற்றும் தரவு கட்டமைப்புகளை தீர்த்தல்.",
    "exp.ach1.points": "உலகளவில் முதல் 7%",
    "exp.ach2.title": "OpenCV வெற்றியாளர்",
    "exp.ach2.desc": "முக அங்கீகார வருகைப் பதிவிற்காக கல்லூரி முதல்வரிடம் முதல் பரிசு பெற்றது.",
    "exp.ach2.points": "புதுமை சாம்பியன்",
    "exp.ach3.title": "திறந்த மூல பங்களிப்பாளர்",
    "exp.ach3.desc": "பிரபலமான RAG செயலிகள் மற்றும் பயனர் இடைமுகங்களில் பிழைகளைத் திருத்தியது.",
    "exp.ach3.points": "செயலில் உள்ள கிட்ஹப்",
    "exp.ach4.title": "சிறந்த கல்வி நிலை",
    "exp.ach4.desc": "பொறியியல் படிப்பில் தொடர்ந்து 9.2 சிஜிபிஏ சிறந்த மதிப்பெண்களைப் பெற்றது.",
    "exp.ach4.points": "9.2 கோர் சிஜிபிஏ",
    "contact.subtitle": "நேரத்தை முன்பதிவு செய்யவோ அல்லது வாட்ஸ்அப் மூலம் தொடர்புகொள்ளவோ.",
    "contact.nodeSpecifications": "முனையின் விவரக்குறிப்புகள்",
    "contact.hqCoordinate": "தலைமையகம்",
    "contact.location": "ஹைதராபாத், தெலுங்கானா, இந்தியா",
    "contact.terminalEmail": "மின்னஞ்சல் முகவரி",
    "contact.whatsapp": "நேரடி வாட்ஸ்அப்",
    "contact.connectOuterSpace": "பிற இணைப்புகள்",
    "contact.directTransmission": "நேரடி தகவல் அனுப்ப",
    "contact.identity": "உங்கள் அடையாளம்",
    "contact.returnMail": "மின்னஞ்சல் முகவரி",
    "contact.payload": "உள்ளடக்கம்",
    "contact.placeholderIdentity": "எ.கா: வேலை வழங்குபவர், மேலாளர்",
    "contact.placeholderEmail": "எ.கா: user@domain.com",
    "contact.placeholderMessage": "உங்கள் தகவலை இங்கே தட்டச்சு செய்யவும்...",
    "contact.transmitBtn": "தகவலை அனுப்பு",
    "contact.transmitting": "தகவல் பரிமாற்றம் செய்யப்படுகிறது...",
    "contact.bookingNode": "ஆன்லைன் முன்பதிவு",
    "contact.targetDate": "தேதியைத் தேர்ந்தெடுக்கவும் :",
    "contact.preferredSlot": "நேரத்தைத் தேர்ந்தெடுக்கவும் :",
    "contact.scheduleBtn": "நேரத்தை உறுதி செய்",
    "contact.success": "தகவல் வெற்றிகரமாக அனுப்பப்பட்டது! கணேஷ் விரைவில் பதிலளிப்பார்.",
    "contact.errorFail": "தகவலை அனுப்புவதில் பிழை. மீண்டும் முயற்சிக்கவும்.",
    "contact.errorOffline": "சேவையக இணைப்பு துண்டிக்கப்பட்டுள்ளது."
  },
  bn: {
    "nav.home": "হোম",
    "nav.about": "সম্পর্কে",
    "nav.skills": "দক্ষতা",
    "nav.projects": "প্রজেক্ট",
    "nav.certifications": "শংসাপত্র",
    "nav.contact": "যোগাযোগ",
    "about.heading": "গণেশ সম্পর্কে",
    "skills.heading": "প্রযুক্তিগত দক্ষতা",
    "projects.heading": "ভবিষ্যতের প্রজেক্ট",
    "certs.heading": "যাচাইকৃত অর্জন",
    "experience.heading": "সময়ক্রম ও বিজয়",
    "contact.heading": "যোগাযোগ করুন",
    "hud.status": "সিস্টেম_ঠিক",
    "hud.timezone": "ইউটিসি",
    "role.0": "এআই ও ডাটা সায়েন্স ইঞ্জিনিয়ার",
    "role.1": "মেশিন লার্নিং অনুরাগী",
    "role.2": "জেনারেটিভ এআই ডেভেলপার",
    "role.3": "ফুল স্ট্যাক ডেভেলপার",
    "hero.coreIntelligence": "কোর ইন্টেলিজেন্স প্রস্তুত",
    "hero.name": "গণেশ এন্য়ারাম",
    "hero.description": "এআই এবং ডাটা সায়েন্সে বি.টেক বিশেষজ্ঞ। পরিসংখ্যানগত নির্ভুলতার সাথে আধুনিক নিউরাল আর্কিটেকচারের সমন্বয় ঘটিয়ে সমাধান তৈরি করছেন।",
    "hero.contactBtn": "গণেশের সাথে যোগাযোগ করুন",
    "hero.resumeBtn": "জীবনবৃত্তান্ত বিশ্লেষণ করুন",
    "hero.stats.aiChats": "এআই চ্যাটবট ও এজেন্ট",
    "hero.stats.solved": "কোডিং সমাধান সম্পন্ন",
    "hero.stats.systemViews": "সিস্টেম ভিউ",
    "hero.stats.won": "হ্যাকথনে প্লেসমেন্ট ও জয়",
    "about.careerVision": "চাকরির লক্ষ্য ও দূরদর্শিতা",
    "about.careerVisionDesc1": "এআই এবং ডাটা সায়েন্সের একজন উৎসাহী বি.টেক ছাত্র হিসেবে, আমার লক্ষ্য বুদ্ধিমান সহকারী এবং আরএজি আর্কিটেকচার তৈরি করা।",
    "about.careerVisionDesc2": "আমি জটিল গাণিতিক এবং পরিসংখ্যান মডেলকে অত্যন্ত অপ্টিমাইজড সফটওয়্যারে রূপান্তর করতে পছন্দ করি।",
    "about.academicHonors": "একাডেমিক সম্মাননা",
    "about.academicHistory": "একাডেমিক ইতিহাস",
    "about.engineeringFocus": "বিশেষায়িত ইঞ্জিনিয়ারিং ফোকাস",
    "about.edu1.degree": "আর্টিফিশিয়াল ইন্টেলিজেন্স ও ডাটা সায়েন্সে বি.টেক",
    "about.edu1.institution": "বর্ধমান কলেজ অব ইঞ্জিনিয়ারিং, হায়দ্রাবাদ",
    "about.edu1.summary": "উন্নত মেশিন লার্নিং, ডিপ লার্নিং, জেনারেটিভ এআই মডেল এবং ক্রাউড আর্কিটেকচারে মনোযোগ। জিপিএ: ৯.২/১০।",
    "about.edu2.degree": "ইন্টারমিডিয়েট (এমপিসি)",
    "about.edu2.institution": "এসআর জুনিয়র কলেজ",
    "about.edu2.summary": "গণিত, পদার্থবিদ্যা এবং রসায়নে ৯৮.২% নম্বর সহ একাডেমিক শ্রেষ্ঠত্ব অর্জন।",
    "about.ach1": "হ্যাকইন্ডিয়া ২০২৫-এর জাতীয় এলিট স্তরে স্থান লাভ।",
    "about.ach2": "স্মার্ট ওপেনসিভি অ্যাটেনডেন্স ট্র্যাকারের জন্য প্রথম পুরস্কার।",
    "about.ach3": "ধারাবাহিক শ্রেষ্ঠত্বের জন্য একাডেমিক স্কলারশিপ।",
    "about.ach4": "লিটকোড ও হ্যাকারর‌্যাঙ্কে ৪০০-র বেশি কোডিং সমস্যার সমাধান।",
    "about.exp1.title": "জেনারেটিভ এআই সিস্টেম",
    "about.exp1.desc": "এলএলএম, ফাইন-টিউনিং, আরএজি এবং এআই এজেন্টদের ব্যবহার করে শক্তিশালী সিস্টেম তৈরি।",
    "about.exp2.title": "প্রেডিক্টিভ অ্যানালিটিক্স ও এমএল",
    "about.exp2.desc": "শ্রেণীবিভাগ, রিগ্রেশন পাইপলাইন, পরিসংখ্যানগত বিশ্লেষণ এবং ক্লাস্টারিং।",
    "about.exp3.title": "এজেন্টিক ইঞ্জিনিয়ারিং",
    "about.exp3.desc": "crewAI, LangChain এবং LangGraph ব্যবহার করে মাল্টি-এজেন্ট নেটওয়ার্ক তৈরি।",
    "about.exp4.title": "শক্তিশালী ফুল-স্ট্যাক অ্যাপস",
    "about.exp4.desc": "React, Next.js, Node.js এবং ডেটাবেস ব্যবহার করে ইন্টারেক্টিভ ড্যাশবোর্ড এবং এপিআই ডিজাইন।",
    "skills.subtitle": "হ্যাকথন, একাডেমিক ল্যাব এবং ওপেন সোর্স অ্যাপ্লিকেশনের মাধ্যমে মূল্যায়িত দক্ষতা।",
    "skills.category": "বিভাগ",
    "skills.cat1": "প্রোগ্রামিং",
    "skills.cat2": "এআই ও এমএল",
    "skills.cat3": "ডেভেলপমেন্ট",
    "skills.cat4": "ক্লাউড ও ডেভঅপস",
    "projects.subtitle": "আজকের যুগে এজ কম্পিউটিং এবং আধুনিক জেনারেটিভ পাইপলাইনের সাহায্যে তৈরি সমাধান।",
    "projects.filterAll": "সব",
    "projects.filterAIML": "এআই ও এমএল",
    "projects.filterGenAI": "জেনারেটিভ এআই",
    "projects.filterFullStack": "ফুল-স্ট্যাক",
    "projects.proj1.title": "এজেন্টিক রিজিউমে অ্যানালাইজার ও এটিএস বেঞ্চমার্কার",
    "projects.proj1.desc": "উন্নত আরএজি পাইপলাইন যা চাকরির বর্ণনার সাথে রিজিউমে বিশ্লেষণ করে সঠিক এটিএস র্যাঙ্কিং দেয়।",
    "projects.proj1.metric": "ম্যাচিং প্রিসিশন গেইন",
    "projects.proj2.title": "স্মার্ট ওপেনসিভি এজ অ্যাটেনডেন্স ট্র্যাকার",
    "projects.proj2.desc": "ক্লাসরুমের উপস্থিতি ট্র্যাক করার জন্য উচ্চ দক্ষতার ফেসিয়াল রিকগনিশন।",
    "projects.proj2.metric": "ট্র্যাকিং ফ্রেম ডিলে",
    "projects.proj3.title": "মাল্টি-এজেন্ট পোর্টফোলিও কথোপকথন সহকারী",
    "projects.proj3.desc": "গণেশের প্রতিনিধিত্বকারী ডিজিটাল অবতার, ভয়েস রেসপন্স সহ সজ্জিত।",
    "projects.proj3.metric": "কুয়েরি রেসলিউশন অ্যাক্যুরেসি",
    "projects.proj4.title": "স্বায়ত্তশাসিত জেনারেটিভ মাল্টি-মোডাল সহকারী",
    "projects.proj4.desc": "স্টেবল ডিফিউশন এবং কাস্টম সিস্টেম ফিল্টার সহ কথোপকথন ভিত্তিক টেক্সট ও ইমেজ সিস্টেম।",
    "projects.proj4.metric": "ইমেজ সিন্থেসিস ল্যাটেন্সি",
    "projects.proj5.title": "ডায়নামিক স্টুডেন্ট পারফরম্যান্স অ্যানালিটিক্স প্যানেল",
    "projects.proj5.desc": "D3/Recharts চালিত ড্যাশবোর্ড যা জিপিএ ট্রেন্ড এবং স্কোর প্রদর্শন করে।",
    "projects.proj5.metric": "ডাটাবেস কুয়েরি ফেচ ডিলে",
    "certs.subtitle": "অনুমোদিত শিল্প প্রতিষ্ঠান দ্বারা যাচাইকৃত ক্লাউড এবং ডিপ লার্নিং সার্টিফিকেট।",
    "certs.verifyBtn": "শংসাপত্র যাচাই করুন",
    "exp.subtitle": "হ্যাকথন, প্লেসমেন্ট প্রস্তুতি এবং গবেষণা ইন্টার্নশিপের বাস্তব ল্যাব বিবরণ।",
    "exp.timelineTitle": "ক্যারিয়ার টাইমলাইন ও ল্যাবস",
    "exp.achievementsTitle": "মূল অর্জনসমূহ",
    "exp.item1.role": "জেনারেটিভ এআই গবেষণা ইন্টার্ন",
    "exp.item1.org": "হেক্সামাইন্ড রিসার্চ ল্যাবস",
    "exp.item1.bullet1": "crewAI-এর সাথে কাস্টম এজেন্ট তৈরি করার ফলে ডেটা পার্সিং ৩৫% দ্রুত হয়েছে।",
    "exp.item1.bullet2": "স্থানীয় সিপিইউ-তে এলএলএম ল্যাটেন্সি কমাতে কোয়ান্টাইজেশন অপ্টিমাইজেশন।",
    "exp.item1.bullet3": "বিশ্ববিদ্যালয়ের গবেষণার জন্য একটি ইন্টারেক্টিভ আরএজি ইন্টারফেস তৈরি।",
    "exp.item2.role": "ফুল স্ট্যাক ইঞ্জিনিয়ার (ফ্রিল্যান্স)",
    "exp.item2.org": "পরামর্শ চুক্তি (স্থানীয় স্টার্টআপ)",
    "exp.item2.bullet1": "React 19, Tailwind CSS এবং সুরক্ষিত নোড এপিআই দিয়ে রোগী বুকিং ড্যাশবোর্ড তৈরি।",
    "exp.item2.bullet2": "এপিআই ল্যাটেন্সি ২৪০মিলিসেকেন্ড থেকে কমিয়ে ৭৫মিলিসেকেন্ডে নামিয়ে আনা।",
    "exp.item3.role": "হ্যাকইন্ডিয়া জাতীয় হ্যাকথন প্রতিযোগী",
    "exp.item3.org": "জাতীয় এলিট ২% গিল্ড",
    "exp.item3.bullet1": "৩৬ ঘণ্টারও কম সময়ে একটি বিকেন্দ্রীকৃত যাচাইকরণ ইঞ্জিন তৈরি করা।",
    "exp.item3.bullet2": "৫০০০+ এরও বেশি আবেদনকারীর মধ্যে শীর্ষ ২% স্থানে অবস্থান করা।",
    "exp.ach1.title": "লিটকোড বিশেষজ্ঞ",
    "exp.ach1.desc": "৪০০+ অ্যালগরিদমিক এবং কোডিং সমস্যার সমাধান। গ্রাফ, বাইনারি সার্চ এবং গতিশীল মডেলগুলিতে অভিজ্ঞ।",
    "exp.ach1.points": "বিশ্বব্যাপী শীর্ষ ৭%",
    "exp.ach2.title": "স্মার্ট ওপেনসিভি বিজয়ী",
    "exp.ach2.desc": "ফেসিয়াল রিকগনিশন অ্যাটেনডেন্স ট্র্যাকারের জন্য প্রথম পুরস্কার।",
    "exp.ach2.points": "উদ্भावন চ্যাম্পিয়ন",
    "exp.ach3.title": "ওপেন সোর্স অবদানকারী",
    "exp.ach3.desc": "আরএजी পাইপলাইন এবং রিঅ্যাক্ট র‌্যাপারগুলিতে পারফরম্যান্সের উন্নতি।",
    "exp.ach3.points": "সক্রিয় গিটহাব প্রোফाइल",
    "exp.ach4.title": "এলিট একাডেমিক পর্যায়",
    "exp.ach4.desc": "ধারাবাহিকভাবে সমেস্টার জিপিএ ৯.২ ধরে রাখার জন্য স্কলারশিপ লাভ।",
    "exp.ach4.points": "৯.२ কোর সিজিপিএ",
    "contact.subtitle": "মিটিং বুক করুন, সরাসরি নোড মেসেজ পাঠান, বা হোয়াটসঅ্যাপ চ্যাট শুরু করুন।",
    "contact.nodeSpecifications": "নোড স্পেসিফিকেশন",
    "contact.hqCoordinate": "প্রধান কার্যালয়",
    "contact.location": "হায়দ্রাবাদ, তেলেঙ্গানা, ভারত",
    "contact.terminalEmail": "টার্মিনাল ইমেল",
    "contact.whatsapp": "হোয়াটসঅ্যাপ হটলিঙ্ক",
    "contact.connectOuterSpace": "বহিরাগত যোগাযোগ",
    "contact.directTransmission": "সরাসরি নোড ট্রান্সমিশন",
    "contact.identity": "আপনার পরিচয়",
    "contact.returnMail": "ফেরত ইমেল ঠিকানা",
    "contact.payload": "বার্তার বিবরণ",
    "contact.placeholderIdentity": "যেমন- রিক্রুটার, টেক লিড",
    "contact.placeholderEmail": "যেমন- lead@google.com",
    "contact.placeholderMessage": "ইন্টারভিউ সিডিউল, প্রজেক্ট রিভিউ বা কাজের বিষয়ে জিজ্ঞাসা করুন...",
    "contact.transmitBtn": "লক এবং সেন্ড করুন",
    "contact.transmitting": "ভেক্টর ট্রান্সমিট হচ্ছে...",
    "contact.bookingNode": "স্বয়ংক্রিয় মিটিং হাব",
    "contact.targetDate": "তারিখ নির্বাচন করুন:",
    "contact.preferredSlot": "পছন্দসই সময় স্লট:",
    "contact.scheduleBtn": "মিটিং বুক করুন",
    "contact.success": "বার্তা সফলভাবে পাঠানো হয়েছে। গণেশ খুব শীঘ্রই প্রতিক্রিয়া জানাবেন!",
    "contact.errorFail": "বার্তা পাঠাতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    "contact.errorOffline": "অফলাইন ত্রুটি। সার্ভার ক্লাস্টার সংযোগ परीक्षा করুন।"
  },
  mr: {
    "nav.home": "मुख्यपृष्ठ",
    "nav.about": "माझ्याबद्दल",
    "nav.skills": "कौशल्ये",
    "nav.projects": "प्रकल्प",
    "nav.certifications": "प्रमाणपत्रे",
    "nav.contact": "संपर्क",
    "about.heading": "गणेशबद्दल",
    "skills.heading": "तांत्रिक कौशल्ये",
    "projects.heading": "प्रकल्प आणि विकास",
    "certs.heading": "प्रमाणित यश",
    "experience.heading": "अनुभव आणि यश",
    "contact.heading": "संपर्क करा",
    "hud.status": "सिस्टम_ठीक",
    "hud.timezone": "UTC",
    "role.0": "एआई आणि डेटा सायन्स अभियंता",
    "role.1": "मशीन लर्निंग उत्साही",
    "role.2": "जनरेटिव्ह एआय डेव्हलपर",
    "role.3": "फुल स्टॅक डेव्हलपर",
    "hero.coreIntelligence": "मुख्य बुद्धिमत्ता सज्ज",
    "hero.name": "गणेश एन्याराम",
    "hero.description": "एआय आणि डेटा सायन्समध्ये बी.टेक तज्ज्ञ. अचूकतेसह अत्याधुनिक न्यूरल आर्किटेक्चर वापरून स्केलेबल सोल्यूशन्स तयार करत आहे.",
    "hero.contactBtn": "संपर्क साधा",
    "hero.resumeBtn": "बायोडाटा मिळवा",
    "hero.stats.aiChats": "एआय चॅटबॉट्स आणि एजंट्स",
    "hero.stats.solved": "सोडवलेले कोडिंग प्रश्न",
    "hero.stats.systemViews": "सिस्टम व्ह्यूज",
    "hero.stats.won": "हॅकथॉन मधील यश",
    "about.careerVision": "करिअरची उद्दिष्टे",
    "about.careerVisionDesc1": "माझे उद्दिष्ट बुद्धिमान कॉग्निटिव्ह असिस्टंट्स, प्रगत RAG आर्किटेक्चर्स आणि उत्कृष्ट वापरकर्ता अनुभव तयार करणे आहे.",
    "about.careerVisionDesc2": "मी गुंतागुंतीच्या गणितीय आणि सांख्यिकी मॉडेल्सचे अत्यंत कार्यक्षम आणि स्केलेबल सॉफ्टवेअरमध्ये रूपांतर करतो, जे लॅटन्सी कमी आणि कार्यक्षमता जास्त ठेवते.",
    "about.academicHonors": "शैक्षणिक सन्मान",
    "about.academicHistory": "शैक्षणिक इतिहास",
    "about.engineeringFocus": "विशेष अभियांत्रिकी लक्ष केंद्रित",
    "about.edu1.degree": "बी.टेक - आर्टिफिशियल इंटेलिजन्स आणि डेटा सायन्स",
    "about.edu1.institution": "वर्धमान कॉलेज ऑफ इंजिनियरिंग, हैदराबाद",
    "about.edu1.summary": "प्रगत मशीन लर्निंग, डीप लर्निंग, जनरेटिव्ह एआय मॉडेल्स आणि क्लाउड आर्किटेक्चर यावर लक्ष केंद्रित. सीजीपीए: ९.२/१०.",
    "about.edu2.degree": "इंटरमीडिएट शिक्षण (MPC)",
    "about.edu2.institution": "एसआर ज्युनियर कॉलेज",
    "about.edu2.summary": "गणित, भौतिकशास्त्र आणि रसायनशास्त्र विषयात ९८.२% गुणांसह शैक्षणिक उत्कृष्टता मिळवली.",
    "about.ach1": "हॅकइंडिया २०२५ मध्ये राष्ट्रीय स्तरावर निवड.",
    "about.ach2": "स्मार्ट OpenCV हजेरी ट्रॅकरसाठी महाविद्यालयात प्रथम पारितोषिक.",
    "about.ach3": "उत्कृष्ट शैक्षणिक कामगिरीसाठी सातत्यपूर्ण शिष्यवृत्ती.",
    "about.ach4": "LeetCode आणि HackerRank वर ४०० हून अधिक कोडिंग समस्या सोडवल्या.",
    "about.exp1.title": "जनरेटिव्ह एआय सिस्टिम्स",
    "about.exp1.desc": "LLMs, फाईन-ट्यूनिंग, RAG आणि एजंट फ्रेमवर्क वापरून मजबूत सिस्टिम्सची निर्मिती.",
    "about.exp2.title": "प्रेडिक्टिव्ह अ‍ॅनालिटिक्स आणि ML",
    "about.exp2.desc": "वर्गीकरण, रिग्रेशन पाईपलाईन्स, सांख्यिकीय विश्लेषण आणि डेटासेट रूपांतरण.",
    "about.exp3.title": "एजेंट इंजिनिअरिंग",
    "about.exp3.desc": "crewAI, LangChain आणि LangGraph चा वापर करून मल्टि-एजंट नेटवर्क डिझाइन करणे.",
    "about.exp4.title": "मजकूत फुल-स्टॅक अ‍ॅप्स",
    "about.exp4.desc": "React, Next.js, Node.js आणि डेटाबेस वापरून प्रतिसाद देणारे डॅशबोर्ड आणि सर्व्हर API डिझाइन करणे.",
    "skills.subtitle": "हॅकथॉन, शैक्षणिक लॅब आणि ओपन-सोर्स अ‍ॅप्लिकेशन्सद्वारे तांत्रिक कौशल्य मूल्यांकन.",
    "skills.category": "श्रेणी",
    "skills.cat1": "प्रोग्रामिंग",
    "skills.cat2": "एआय आणि एमएल",
    "skills.cat3": "डेव्हलपमेंट",
    "skills.cat4": "क्लाउड आणि डेव्हऑप्स",
    "projects.subtitle": "एज कॉम्प्युटिंग आणि अत्याधुनिक जनरेटिव्ह तंत्रज्ञानासह तयार सोल्यूशन्स.",
    "projects.filterAll": "सर्व",
    "projects.filterAIML": "एआय आणि एमएल",
    "projects.filterGenAI": "जनरेटिव्ह एआय",
    "projects.filterFullStack": "फुल-स्टॅक",
    "projects.proj1.title": "एजंंट नॅव्हिगेटर बायोडाटा विश्लेषक (ATS)",
    "projects.proj1.desc": "बायोडाटा आणि जॉब प्रोफाईलची तुलना करणारे प्रगत RAG प्रणाली.",
    "projects.proj1.metric": "अचूकता सुधारणा",
    "projects.proj2.title": "स्मार्ट OpenCV एज हजेरी प्रणाली",
    "projects.proj2.desc": "OpenCV आणि फायरस्टोअरच्या साहाय्याने जलद चेहरा ओळख आणि हजेरी ट्रॅकर.",
    "projects.proj2.metric": "इन्फरन्स लॅटन्सी",
    "projects.proj3.title": "मल्टी-एजंट संवाद मित्र",
    "projects.proj3.desc": "आवाजाची क्षमता असलेला गणेशचा डिजिटल अवतार.",
    "projects.proj3.metric": "चौकशीचे अचूक निवारण",
    "projects.proj4.title": "ऑटोनॉमस जनरेटिव्ह मल्टी-मॉडल असिस्टंट",
    "projects.proj4.desc": "Stable Diffusion वापरून मजकूर आणि चित्रांचे ऑटोमेशन.",
    "projects.proj4.metric": "चित्र निर्मिती वेळ",
    "projects.proj5.title": "डायनॅमिक विद्यार्थी कामगिरी डॅशबोर्ड",
    "projects.proj5.desc": "गुण आणि वर्तनाचा आढावा घेणारे D3 आणि Recharts आणि डॅशबोर्ड.",
    "projects.proj5.metric": "डेटाबेस लॅटन्सी",
    "certs.subtitle": "अधिकृत संस्थांमार्फत सत्यापित क्लाउड आणि डीप लर्निंग प्रमाणपत्रे.",
    "certs.verifyBtn": "प्रमाणपत्र तपासा",
    "exp.subtitle": "व्यावसायिक अनुभव, हॅकथॉन तयारी आणि महत्त्वाचे टप्पे.",
    "exp.timelineTitle": "करिअरचा प्रवास",
    "exp.achievementsTitle": "प्रमुख उपलब्धी",
    "exp.item1.role": "जनरेटिव्ह एआय संशोधन इंटर्न",
    "exp.item1.org": "HexaMind Research Labs",
    "exp.item1.bullet1": "crewAI च्या साहाय्याने ३५% कार्यक्षमतेने डेटा विश्लेषण सुधारणारे एजंट्स विकसित केले.",
    "exp.item1.bullet2": "स्थानिक सीपीयू लॅटन्सी कमी करण्यासाठी क्वांटायझेशचा वापर करून मॉडेल्स सुधारित केले.",
    "exp.item1.bullet3": "प्रकल्प डेटा शोध सुलभ करण्यासाठी LangChain चा वापर करून नवीन RAG संवाद प्रणाली तयार केली.",
    "exp.item2.role": "फुल स्टॅक अभियंता (फ्रीलान्स)",
    "exp.item2.org": "स्थानिक स्टार्टअप्सना तांत्रिक सल्लागार",
    "exp.item2.bullet1": "React 19 आणि Node.js वापरून बुकिंग आणि शेड्युलिंग डॅशबोर्ड तयार केले.",
    "exp.item2.bullet2": "डेटाबेस आणि API लॅटन्सी २४०ms वरून ७५ms पर्यंत कमी केली.",
    "exp.item3.role": "हॅकइंडिया राष्ट्रीय पातळीवरील फायनलिस्ट",
    "exp.item3.org": "राष्ट्रीय स्तरावरील शीर्ष २% चमू",
    "exp.item3.bullet1": "३६ तासांपेक्षा कमी वेळेत अचूक डेटा पडताळणी प्रणालीचे प्रोटोटाईप डिझाइन केले.",
    "exp.item3.bullet2": "देशभरातील हजारो विद्यार्थ्यांमधून शीर्ष २% मध्ये स्थान मिळविले.",
    "exp.ach1.title": "LeetCode तज्ज्ञ",
    "exp.ach1.desc": "४०० हून अधिक मधील प्रगत डेटा स्ट्रक्चर्स आणि अल्गोरिदम समस्या सोडवल्या.",
    "exp.ach1.points": "जागतिक स्तरावर शीर्ष ७%",
    "exp.ach2.title": "OpenCV विजेता",
    "exp.ach2.desc": "स्वयंचलित हजेरी रेकॉर्ड कॅमेरा प्रणालीसाठी महाविद्यालयात प्रथम पुरस्कार.",
    "exp.ach2.points": "इनोव्हेशन चॅम्पियन",
    "exp.ach3.title": "ओपन सोर्स योगदानकर्ता",
    "exp.ach3.desc": "प्रख्यात RAG आणि React घटकांसाठी तांत्रिक सुधारणा आणि दुरुस्त्या जोडल्या.",
    "exp.ach3.points": "सक्रिय गिटहब प्रोफाईल",
    "exp.ach4.title": "उत्कृष्ट शैक्षणिक रेकॉर्ड",
    "exp.ach4.desc": "प्रत्येक सेमिस्टरमध्ये यशस्वीरित्या ९.२ CGPA गुणवत्ता टिकवून ठेवली.",
    "exp.ach4.points": "९.२ कोर CGPA",
    "contact.subtitle": "बैठक बुक करा, सुरक्षित थेट संदेश पाठवा किंवा व्हॉट्सअ‍ॅपवर संपर्क साधा.",
    "contact.nodeSpecifications": "तांत्रिक वैशिष्ट्ये",
    "contact.hqCoordinate": "मुख्य केंद्र",
    "contact.location": "हैदराबाद, तेलंगणा, भारत",
    "contact.terminalEmail": "ईमेल पत्ता",
    "contact.whatsapp": "थेट व्हॉट्सअ‍ॅप दुवा",
    "contact.connectOuterSpace": "इतर नेटवर्क्स",
    "contact.directTransmission": "बैठक बुक करा",
    "contact.identity": "तुमची ओळख",
    "contact.returnMail": "तुमचा ईमेल",
    "contact.payload": "पाठवायचा संदेश",
    "contact.placeholderIdentity": "उदा: रिक्रूटर किंवा प्रकल्प व्यवस्थापक",
    "contact.placeholderEmail": "उदा: lead@company.com",
    "contact.placeholderMessage": "नोकरीच्या संधी किंवा बैठकांविषयी माहिती लिहा...",
    "contact.transmitBtn": "संदेश पाठवा",
    "contact.transmitting": "माहिती पाठवत आहे...",
    "contact.bookingNode": "स्वयंचलित बैठक शेड्युलिंग",
    "contact.targetDate": "दिनांक निवडा:",
    "contact.preferredSlot": "योग्य वेळ निवडा:",
    "contact.scheduleBtn": "बैठक बुक करा",
    "contact.success": "संदेश यशस्वीरित्या पाठवला आहे! गणेश लवकरच उत्तर देईल.",
    "contact.errorFail": "संदेश पाठवण्यात अपयश. पुन्हा प्रयत्न करा.",
    "contact.errorOffline": "तुम्ही सध्या ऑफलाइन आहात. नेटवर्क कनेक्शन तपासा."
  },
  kn: {
    "nav.home": "ಮುಖಪುಟ",
    "nav.about": "ನನ್ನ ಬಗ್ಗೆ",
    "nav.skills": "ಕೌಶಲ್ಯಗಳು",
    "nav.projects": "ಯೋಜನೆಗಳು",
    "nav.certifications": "ಪ್ರಮಾಣಪತ್ರಗಳು",
    "nav.contact": "ಸಂಪರ್ಕಿಸಿ",
    "about.heading": "ಗಣೇಶ್ ಬಗ್ಗೆ",
    "skills.heading": "ತಾಂತ್ರಿಕ ಕೌಶಲ್ಯಗಳು",
    "projects.heading": "ಅಭಿವೃದ್ಧಿ ಯೋಜನೆಗಳು",
    "certs.heading": "ಪ್ರಮಾಣಪತ್ರಗಳು",
    "experience.heading": "ಅನುಭವ ಮತ್ತು ಸಾಧನೆಗಳು",
    "contact.heading": "ಸಂಪರ್ಕಕ್ಕೆ ಬನ್ನಿ",
    "hud.status": "ಸಿಸ್ಟಮ್_ಸರಿ"
  },
  ml: {
    "nav.home": "ഹോം",
    "nav.about": "എന്നെക്കുറിച്ച്",
    "nav.skills": "കഴിവുകൾ",
    "nav.projects": "പ്രോജക്റ്റുകൾ",
    "nav.certifications": "സർട്ടിഫിക്കറ്റുകൾ",
    "nav.contact": "ബന്ധപ്പെടുക",
    "about.heading": "ഗണേഷിനെക്കുറിച്ച്",
    "skills.heading": "സാങ്കേതിക കഴിവുകൾ",
    "projects.heading": "പ്രോജക്റ്റുകൾ",
    "certs.heading": "സർട്ടിഫിക്കറ്റുകൾ",
    "experience.heading": "അനുഭവവും നേട്ടങ്ങളും",
    "contact.heading": "ബന്ധപ്പെടുക",
    "hud.status": "സിസ്റ്റം_ശരി"
  },
  gu: {
    "nav.home": "મુખ્ય પૃષ્ઠ",
    "nav.about": "મારા વિશે",
    "nav.skills": "કૌશલ્ય",
    "nav.projects": "પ્રોજેક્ટ્સ",
    "nav.certifications": "પ્રમાણપત્રો",
    "nav.contact": "સંપર્ક",
    "about.heading": "ગણેશ વિશે",
    "skills.heading": "તકનીકી કૌશલ્ય",
    "projects.heading": "પ્રોજેક્ટ્સ અને વિકાસ",
    "certs.heading": "પ્રમાણપત્રો",
    "experience.heading": "અનુભવ અને સિદ્ધિઓ",
    "contact.heading": "સંપર્ક કરો",
    "hud.status": "સિસ્ટમ_ઓકે"
  },
  pa: {
    "nav.home": "ਮੁੱਖ ਪੰਨਾ",
    "nav.about": "ਮੇਰੇ ਬਾਰੇ",
    "nav.skills": "ਹੁਨਰ",
    "nav.projects": "ਪ੍ਰੋਜੈਕਟ",
    "nav.certifications": "ਸਰਟੀਫਿਕੇਟ",
    "nav.contact": "ਸੰਪਰਕ",
    "about.heading": "ਗਣੇਸ਼ ਬਾਰੇ",
    "skills.heading": "ਤਕਨੀਕੀ ਹੁਨਰ",
    "projects.heading": "ਪ੍ਰੋਜੈਕਟ",
    "certs.heading": "ਸਰਟੀਫਿਕੇਟ",
    "experience.heading": "ਤਜਰਬਾ ਅਤੇ ਪ੍ਰਾਪਤੀਆਂ",
    "contact.heading": "ਸੰਪਰਕ ਕਰੋ",
    "hud.status": "ਸਿਸਟમ_ਠੀਕ"
  }
};

// Build flattened translations with dynamic en fallback at module load time
const translations: Record<Language, Record<string, string>> = {} as any;
const languages: Language[] = ["en", "hi", "te", "ta", "bn", "mr", "kn", "ml", "gu", "pa"];

languages.forEach((lang) => {
  const extra = (lang === "kn" || lang === "ml" || lang === "gu" || lang === "pa")
    ? extraTranslations[lang]
    : {};
  translations[lang] = {
    ...baseTranslations.en,
    ...(baseTranslations[lang] || {}),
    ...extra,
  } as Record<string, string>;
});

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("portfolio-lang");
    const allowed: Language[] = ["en", "hi", "te", "ta", "bn", "mr", "kn", "ml", "gu", "pa"];
    return (saved && allowed.includes(saved as any) ? saved : "en") as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("portfolio-lang", lang);
  };

  const t = (key: string, defaultText?: string): string => {
    const translationSet = translations[language];
    if (translationSet && translationSet[key]) {
      return translationSet[key];
    }
    return defaultText ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div style={{ direction: "ltr" }}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
